#!/bin/bash

# if you want to bind some host directories...
# export SINGULARTY_BINDPATH=/some,/dirs,/to,/bind

DIR=$(dirname  "$0")
CMD=$(basename "$0")
ARG="$@"

# $DIR would not be needed if lolcow.img is exectubale and on the path
singularity exec $DIR/lolcow.img $CMD $ARG